/**
 * 需要按照依赖的顺序
 */
var jsList = [
    "src/src_phz/PHZSyVersion.js",
    "src/src_phz/PHZAI.js",
    "src/src_phz/PHZRoomModel.js",
    "src/src_phz/PHZRoomSound.js",
    "src/src_phz/PHZRoomEffects.js",
    "src/src_phz/PHZBigResultPop.js",
    "src/src_phz/PHZSmallResultPop.js",
    "src/src_phz/PHZMineLayout.js",
    "src/src_phz/PHZLayout.js",
    "src/src_phz/PHZPlayer.js",
    "src/src_phz/PHZCard.js",
    "src/src_phz/PHZRoom.js",
    "src/src_phz/PHZMoneyRoom.js",
    "src/src_phz/PHZMoneyResultPop.js",
    "src/src_phz/PHZHandCardPop.js",
    "src/src_phz/PHZRePlayModel.js",
    "src/src_phz/PHZRePlay.js",
    "src/src_phz/PHZRePlayLayout.js",
    "src/src_phz/PHZSetModel.js",
    "src/src_phz/PaohuziHandCard.js",
    "src/src_phz/PHZSmartFilter.js",
    "src/src_phz/PHZCardIndexArr.js",
    "src/src_phz/PHZCardTypeHuxi.js",
    "src/src_phz/PHZHuBean.js",
    "src/src_phz/PHZHuLack.js",
    "src/src_phz/PHZIndex.js",

    "src/src_phz/src_zhz/ZHZAI.js",
    "src/src_phz/src_zhz/ZHZCard.js",
    "src/src_phz/src_zhz/ZHZMineLayout.js",
    "src/src_phz/src_zhz/ZHZRoom.js",

    "src/src_phz/src_yzchz/YZCHZCard.js",
    "src/src_phz/src_yzchz/YZCHZRoom.js",
    "src/src_phz/src_yzchz/YZCHZLayout.js",

    "src/src_phz/src_ahphz/AHPHZRoom.js",
    "src/src_phz/src_ahphz/AHPHZCard.js",
    "src/src_phz/src_ahphz/AHPHZLayout.js",
    "src/src_phz/src_ahphz/AHPHZMineLayout.js",

    "src/src_phz/src_yjghz/YJGHZBigResultPop.js",
    "src/src_phz/src_yjghz/YJGHZLayout.js",
    "src/src_phz/src_yjghz/YJGHZRePlay.js",
    "src/src_phz/src_yjghz/YJGHZRePlayLayout.js",
    "src/src_phz/src_yjghz/YJGHZRoom.js",
    "src/src_phz/src_yjghz/YJGHZSmallResultPop.js",

    "src/src_phz/src_zzph/ZZPHBigResultPop.js",
    "src/src_phz/src_zzph/ZZPHCard.js",
    "src/src_phz/src_zzph/ZZPHJetton.js",
    "src/src_phz/src_zzph/ZZPHLayout.js",
    "src/src_phz/src_zzph/ZZPHMineLayout.js",
    "src/src_phz/src_zzph/ZZPHPlayer.js",
    "src/src_phz/src_zzph/ZZPHRoom.js",
    "src/src_phz/src_zzph/ZZPHRoomEffects.js",
    "src/src_phz/src_zzph/ZZPHSmallResultPop.js",

    "src/src_phz/src_hyshk/HYSHKLayout.js",

    "src/src_phz/src_hbgzp/HBGZPAI.js",
    "src/src_phz/src_hbgzp/HBGZPCard.js",
    "src/src_phz/src_hbgzp/HBGZPLayout.js",
    "src/src_phz/src_hbgzp/HBGZPMineLayout.js",
    "src/src_phz/src_hbgzp/HBGZPRoom.js",
    "src/src_phz/src_hbgzp/HBGZPRoomEffects.js",
    "src/src_phz/src_hbgzp/HBGZPRoomModel.js",
    "src/src_phz/src_hbgzp/HBGZPReplay.js",
    "src/src_phz/src_hbgzp/HBGZPReplayModel.js",
    "src/src_phz/src_hbgzp/HBGZPRePlayLayout.js",
    "src/src_phz/src_hbgzp/HBGZPSmallResultPop.js",
    "src/src_phz/src_hbgzp/HBGZPBigResult.js",
    "src/src_phz/src_hbgzp/HBGZPSetModel.js",
    "src/src_phz/src_hbgzp/HBGZPPlayer.js",

    "src/src_phz/src_xxeqs/XXEQSRoom.js",
    "src/src_phz/src_xxeqs/XXEQSCard.js",
    "src/src_phz/src_xxeqs/XXEQSLayout.js",

    "src/src_phz/src_nxghz/NXGHZRoom.js",
    'src/src_phz/src_nxghz/NXGHZSmallResultPop.js',
    "src/src_phz/src_nxghz/NXGHZBigResultPop.js",

    "src/src_phz/src_yzlc/YZLCCard.js",
    "src/src_phz/src_yzlc/YZLCBigResultPop.js",
    "src/src_phz/src_yzlc/YZLCLayout.js",
    "src/src_phz/src_yzlc/YZLCMineLayout.js",
    "src/src_phz/src_yzlc/YZLCRoom.js",
    "src/src_phz/src_yzlc/YZLCRoomEffects.js",
    "src/src_phz/src_yzlc/YZLCShowChuo.js",
    "src/src_phz/src_yzlc/YZLCSmallResult.js",
    "src/src_phz/src_yzlc/YZLCRePlayLayout.js",
    "src/src_phz/src_yzlc/YZLCRePlay.js",

    "src/src_phz/src_dybp/DYBPRoom.js",
    "src/src_phz/src_dybp/DYBPLayout.js",
    "src/src_phz/src_dybp/DYBPCard.js",
    "src/src_phz/src_dybp/DYBPMineLayout.js",

    "src/src_phz/src_wcphz/WCPHZRoom.js",
    "src/src_phz/src_wcphz/WCPHZCard.js",
    "src/src_phz/src_wcphz/WCPHZMineLayout.js",

    "src/src_phz/src_axwmq/AXWMQSmallResultPop.js",

    "src/src_phz/src_xplp/XPLPAI.js",
    "src/src_phz/src_xplp/XPLPCard.js",
    "src/src_phz/src_xplp/XPLPLayout.js",
    "src/src_phz/src_xplp/XPLPRoom.js",
    "src/src_phz/src_xplp/XPLPRoomEffects.js",
    "src/src_phz/src_xplp/XPLPRoomModel.js",
    "src/src_phz/src_xplp/XPLPRePlay.js",
    "src/src_phz/src_xplp/XPLPReplayer.js",
    "src/src_phz/src_xplp/XPLPRePlayModel.js",
    "src/src_phz/src_xplp/XPLPRePlayLayout.js",
    "src/src_phz/src_xplp/XPLPSmallResultPop.js",
    "src/src_phz/src_xplp/XPLPBigResultPop.js",
    "src/src_phz/src_xplp/XPLPPlayer.js",
    "src/src_phz/src_xplp/XPLPEffectLayout.js",
    "src/src_phz/src_xplp/XPLPRoomSound.js",
    "src/src_phz/src_xplp/XPLPSmallResultOtherPop.js",
]