/**
 * Created by zhoufan on 2015/8/15.
 */
/**
 * 事件类型定义
 */
var SyEvent = {
	SOCKET_OPENED:"SOCKET_OPENED",
	SOCKET_CLOSED:"SOCKET_CLOSED",
    DIRECT_JOIN_ROOM:"DIRECT_JOIN_ROOM",
    SOCKET_LOGIN_SUCCESS: "SOCKET_LOGIN_SUCCESS",

    CARD_TOUCHED:1,

    JOIN_ROOM:"JOIN_ROOM",
    EXIT_ROOM:"EXIT_ROOM",
    PLAYER_PRO_UPDATE:"PLAYER_PRO_UPDATE",
    PLAYER_STATUS_CHANGE:"PLAYER_STATUS_CHANGE",
    START_PLAY:"START_PLAY",
    LET_OUT_CARD:"LET_OUT_CARD",
    GET_MAJIANG:"GET_MAJIANG",
    CS_GANG_MAJIANG:"CS_GANG_MAJIANG",
    CS_HAIDI:"CS_HAIDI",
    AH_GANG_MAJIANG:"AH_GANG_MAJIANG",
    SELECT_MAJIANG:"SELECT_MAJIANG",
    ONLINE_OFFLINE_NOTIFY:"ONLINE_OFFLINE_NOTIFY",
    SETTLEMENT_SUCCESS:"SETTLEMENT_SUCCESS",
    OVER_PLAY:"OVER_PLAY",
    ROOM_FAST_CHAT:"ROOM_FAST_CHAT",
    LUCKDRAW_TURNNMU:"LUCKDRAW_TURNNMU",
    LUCKDRAW_AWARD:"LUCKDRAW_AWARD",
    USER_AUDIO_READY:"USER_AUDIO_READY",
    USER_AUDIO_PLAY_START:"USER_AUDIO_PLAY_START",
    USER_AUDIO_PLAY_FINISH:"USER_AUDIO_PLAY_FINISH",
    DOUNIU_STATUS_UPDATE:"DOUNIU_STATUS_UPDATE",
    DOUNIU_ZHUANG_RECEIVE:"DOUNIU_ZHUANG_RECEIVE",
    DOUNIU_QI_ZHUANG:"DOUNIU_QI_ZHUANG",
    DOUNIU_XIA_ZHU:"DOUNIU_XIA_ZHU",
    DOUNIU_DECIDE_ZHUANG:"DOUNIU_DECIDE_ZHUANG",
    DOUNIU_LIANG_PAI:"DOUNIU_LIANG_PAI",
    DOUNIU_SELECT_CARD:"DOUNIU_SELECT_CARD",
    DOUNIU_INTERACTIVE_PROP:"DOUNIU_INTERACTIVE_PROP",
    DTZ_UPDATE_GPS:"DTZ_UPDATE_GPS",
    ROOM_ROLD_ICON:"ROOM_ROLD_ICON",

    //PHZ
    FANGZHAO:"FANGZHAO",
    FIX_OUT_CARD:"FIX_OUT_CARD",
    FIX_OUT_CARD_ERROR:"FIX_OUT_CARD_ERROR",
    PHZ_HIDE_ACTION:"PHZ_HIDE_ACTION",
    PHZ_DEAL_CARD:"PHZ_DEAL_CARD",
    PHZ_CLEAN_TING:"PHZ_CLEAN_TING",
    PHZ_HIDE_TING:"PHZ_HIDE_TING",


    //
    NEW_TIPS:"NEW_TIPS",
    UPDATE_TIME:"UPDATE_TIME",
    UPDATE_WAITING:"UPDATE_WAITING",
    UPDATE_MATCH:"UPDATE_MATCH",
    MATCH_INVITE:"MATCH_INVITE",
    MATCH_START:"MATCH_START",
    ID_VDRIFY:"ID_VDRIFY",
    //比赛场
    MATCH_REGISTRY:"MATCH_REGISTRY",
    //战绩分享消息
    RECORD_SHARE:"RECORD_SHARE",
    //清除解散房间框
    DISAGREE_APPLYEXITROOM:"DISAGREE_APPLYEXITROOM",
    BBT_STATUS_UPDATE:"BBT_STATUS_UPDATE",
    BBT_CHUI:"BBT_CHUI",
    SHOW_CHUi:"SHOW_CHUi",
    SHOW_KAIQIANG:"SHOW_KAIQIANG",
    SHOW_ROBBER:"SHOW_ROBBER",
    SHOW_TU:"SHOW_TU",
    BBT_DECIDE_ZHUANG:"BBT_DECIDE_ZHUANG",
    SHOW_SCORE:"SHOW_SCORE",
    CLEAN_CURLUN:"CLEAN_CURLUN",
    //代开刷新
    DAIKAI_REFRESH:"DAIKAI_REFRESH",

    //错误提示
    GET_SERVER_SUC:"GET_SERVER_SUC",
    NOGET_SERVER_ERR:"NOGET_SERVER_ERR",

    //军团
    RFRSH_CY_LIST:"RFRSH_CY_LIST",
    FIX_JT_CHENYUAN:"FIX_JT_CHENYUAN",
    DELETE_JT_CHENYUAN:"DELETE_JT_CHENYUAN",
    FIX_JT_PAIJU:"FIX_JT_PAIJU",
    FIX_JT_ALL_PAIJU:"FIX_JT_ALL_PAIJU",
    UPDATE_XZ_PJ:"UPDATE_XZ_PJ",
    ADD_JT_PAIJU:"ADD_JT_PAIJU",
    UPDATE_ALL_SLECT_PJ:"UPDATE_ALL_SLECT_PJ",
    UPDATE_RENS_MAN:"UPDATE_RENS_MAN",
    DOUNIU_WATCHER_JOINED:"DOUNIU_WATCHER_JOINED",
    JOIN_JT_PANEL:"JOIN_JT_PANEL",
    CREATE_CLUB_OK:"CREATE_CLUB_OK",
    SEND_JOIN_CLUB_OK:"SEND_JOIN_CLUB_OK",
    JOIN_CLUB_OK:"JOIN_CLUB_OK",
    UPDATE_CLUB_LIST:"UPDATE_CLUB_LIST",
    OPEN_BYQ_PANEL:"OPEN_BYQ_PANEL",
    ZYJT_QIE_FU:"ZYJT_QIE_FU",
    MEJT_QIE_FU:"MEJT_QIE_FU",
    DELETE_JT_PAIJU:"DELETE_JT_PAIJU",
    RFRSH_DELETE_LIST:"RFRSH_DELETE_LIST",
    TUICHU_ZQ_ROOM:"TUICHU_ZQ_ROOM",
    OPEN_XG_CY:"OPEN_XG_CY",
    OPEN_SHENPI_PANEL:"OPEN_SHENPI_PANEL",
    ZYJT_ZQ_QIE_FU:"ZYJT_ZQ_QIE_FU",
    ZYJT_JT_QIE_FU:"ZYJT_JT_QIE_FU",
    DOUNIU_TD_PLAYER:"DOUNIU_TD_PLAYER",
    DOUNIU_UPDATE_XYF:"DOUNIU_UPDATE_XYF",
    DELETE_CUOPAI_LAYER:"DELETE_CUOPAI_LAYER",
    UPDATE_BG_YANSE:"UPDATE_BG_YANSE",
    UPDATE_TUOGUAN:"UPDATE_TUOGUAN",
    UPDATE_PB_YANSE:"UPDATE_PB_YANSE",
    UPDATE_YL_LEIX:"UPDATE_YL_LEIX",
    STOP_ALL_QZANIM:"STOP_ALL_QZANIM",
    CLAN_ALL_XIAZHU:"CLAN_ALL_XIAZHU",
    GET_JT_PAIJU:"GET_JT_PAIJU",
    QIANDAO:"QIANDAO",
    OPEN_ACTIVE:"OPEN_ACTIVE",
    SHOW_WANG:"SHOW_WANG",
    SHOW_HTTHREE:"SHOW_HTTHREE",
    REFRESH_CREATE_ROOM_BTN:"REFRESH_CREATE_ROOM_BTN",
    UPDATE_JLB:"UPDATE_JLB",
    DTZ_DEAL_SCORE:"DTZ_DEAL_SCORE",
    GOTO_MONEY_HOME:"GOTO_MONEY_HOME",
    GET_MONEYTODIAMOND_ITEMS:"GET_MONEY_ITEMS",
    GET_DIAMONDTOMONEY_ITEMS:"GET_DIAMONDTOMONEY_ITEMS",
    BUY_MONEY_ITEMS:"BUY_MONEY_ITEMS",
    BUY_DIAMOND_ITEM:"BUY_DIAMOND_ITEM",
    BIND_INVITECODE_SUC:"BIND_INVITECODE_SUC",
    REMOVE_MONEY_LOADING:"REMOVE_MONEY_LOADING",
    REMOVE_MATCH_LOADING:"REMOVE_MATCH_LOADING",
    GET_MONEY_CONFIG:"GET_MONEY_CONFIG",//获取金币场配置
    CLUB_DELETE_ONE:"CLUB_DELETE_ONE",//解散俱乐部房间
    GET_CLUB_ROOMS:"GET_CLUB_ROOMS",//刷新俱乐部房间信息
    CLUB_ROOM_DETAILPOP:"CLUB_ROOM_DETAILPOP",//获取俱乐部房间信息
    RESET_TIME:"RESET_TIME",//重新选择时间区间
    RESET_SINGLE_TIME:"RESET_SINGLE_TIME",//重新选择单个时间
    CLUB_DELETE_TEAM_SUC:"CLUB_DELETE_TEAM_SUC",//删除俱乐部分组成功
    CLUB_CREATE_TEAM_SUC:"CLUB_CREATE_TEAM_SUC",//创建俱乐部分组成功
    UPDATE_CLUB_MEMBER_NUMBER:"UPDATE_CLUB_MEMBER_NUMBER",        //俱乐部分组人员发生变动
    OPEN_TEAM_DETAIL:"OPEN_TEAM_DETAIL",//点击某条俱乐部分组 打开分组详情界面
    UPDATE_CLUB_CHOOSE_PANEL:"UPDATE_CLUB_CHOOSE_PANEL", //刷新显示操作层
    GET_CLUB_BAGS:"GET_CLUB_BAGS",//获取俱乐部的包厢
    GET_CLUB_ALLBAGS:"GET_CLUB_ALLBAGS",//获取所有包厢的信息
    UPDATE_CLUB_BAGS:"UPDATE_CLUB_BAGS",//刷新所有包厢的信息
    CLOSE_CLUB_BAGS:"CLOSE_CLUB_BAGS",//关闭包厢管理
    UPDATE_CLUB_NAME:"UPDATE_CLUB_NAME",//修改俱乐部名称
    UPDATE_BE_INVITE_RED:"UPDATE_BE_INVITE_RED",//刷新被邀请信息红点

    UPDATE_SET_KSCP:"UPDATE_SET_KSCP",
    UPDATE_SET_KQTP:"UPDATE_SET_KQTP",
    UPDATE_SET_YYXZ:"UPDATE_SET_YYXZ",
    UPDATE_SET_CPSD:"UPDATE_SET_CPSD",
    UPDATE_SET_ZPDX:"UPDATE_SET_ZPDX",
    UPDATE_SET_XXXZ:"UPDATE_SET_XXXZ",
    UPDATE_SET_ZPXZ:"UPDATE_SET_ZPXZ",
    UPDATE_SET_PMXZ:"UPDATE_SET_PMXZ",
    UPDATE_SET_ISCP:"UPDATE_SET_ISCP",

    CLUB_SHOW_MATCH_TIP:"CLUB_SHOW_MATCH_TIP", //俱乐部快速匹配提示

    MATCH_ALL_GAMES:"MATCH_ALL_GAMES",//显示比赛场所有场次
    MATCH_APPLY_DETAIL:"MATCH_APPLY_DETAIL",//显示比赛场报名详情
    MATCH_REFRESH_RENSHU:"MATCH_REFRESH_RENSHU",//刷新报名人数
    MATCH_REFRESH_RANK:"MATCH_REFRESH_RANK",//刷新比赛排名
    MATCH_SHOW_TIP:"MATCH_SHOW_TIP",//控制是否显示提示
    MATCH_UP_TIP:"MATCH_UP_TIP",//弹出晋级提示
    MATCH_REFRESH_APPLY:"MATCH_REFRESH_APPLY",//刷新报名状态
    MATCH_RECORD_DATA:"MATCH_RECORD_DATA",//刷新比赛场配置界面
    MATCH_REMOVE_WAIT:"MATCH_REMOVE_WAIT",//移除比赛场等待界面
    MATCH_REFRESH_WAIT:"MATCH_REFRESH_WAIT",//刷新等待界面的数据
    REFRESH_TASKGIFT_LIST:"REFRESH_TASKGIFT_LIST",//刷新礼品兑换列表
    REFRESH_ALLGIFT_NUM:"REFRESH_ALLGIFT_NUM",//刷新礼品兑换列表

    //DDZ
    DECIDE_DIZHU:"DECIDE_DIZHU",
    SHOW_FENSHU:"SHOW_FENSHU",
    CLEAN_XIAZHU:"CLEAN_XIAZHU",
    DDZ_STATUS_UPDATE:"DDZ_STATUS_UPDATE",
    FRESH_HANDLES: "FRESH_HANDLES",
    DI_DIZHU_PAI:"DI_DIZHU_PAI",
    UPDATE_BEI_SHU:"UPDATE_BEI_SHU",
    CHUN_TIAN:"CHUN_TIAN",
    REFRESH_HANDLES:"REFRESH_HANDLES",
    SHOW_ZHANKAI:"SHOW_ZHANKAI",


    //新活动
    OPEN_INTIVE_BTN:"OPEN_INTIVE_BTN",
    GET_CASHNUM_BY_ACTIVITY:"GET_CASHNUM_BY_ACTIVITY",
    REFRESH_BY_ACTIVITY:"REFRESH_BY_ACTIVITY",
    GET_OLDERBACK_GIFT:"GET_OLDERBACK_GIFT",
    GET_OLDERBACK_BTN:"GET_OLDERBACK_BTN",
    GET_NEWUSERHASGIFT_GIFT:"GET_NEWUSERHASGIFT_GIFT",
    GET_NEWUSERHASGIFT_BTN:"GET_NEWUSERHASGIFT_BTN",

    //刷新信用的配置
    UPDATA_CREDIT_PARMS:"UPDATA_CREDIT_PARMS",
    UPDATA_CREDIT_NUM:"UPDATA_CREDIT_NUM",
    UPDATA_CREDIT_RATIO:"UPDATA_CREDIT_RATIO",

    UPDATE_MESSAGE_REDPOINT:"UPDATE_MESSAGE_REDPOINT",//刷新被邀请的红点提示

    UPDATE_SHOW_BAGWANFA:"UPDATE_SHOW_BAGWANFA",//刷新被邀请的红点提示

    CLUB_BAG_FASTJOIN:"CLUB_BAG_FASTJOIN",
    CLUB_BAG_CREATE:"CLUB_BAG_CREATE",
    UPDATE_TUOGUAN_TIME:"UPDATE_TUOGUAN_TIME",


    CHANGE_PDK_CARDS:"CHANGE_PDK_CARDS",
    //打麻将
    SHOW_HU_CARDS:"SHOW_HU_CARDS",
    HIDE_HU_CARDS:"HIDE_HU_CARDS",
    SHOW_TING_CARDS:"SHOW_TING_CARDS",
    SHOW_DESKTTOP_CARDS:"SHOW_DESKTTOP_CARDS",
    CANCEL_SHOW_DESKTTOP_CARDS:"CANCEL_SHOW_DESKTTOP_CARDS",
    FIND_HU_BY_PUTOUT:"FIND_HU_BY_PUTOUT",
    DAPAI_TING:"DAPAI_TING",
    BSMJ_MAI_DIAN:"BSMJ_MAI_DIAN",
    BSMJ_MAI_DIAN_FINISH:"BSMJ_MAI_DIAN_FINISH",
    TJMJ_Ting_STATE:"TJMJ_Ting_STATE",
    TJMJ_Ting:"TJMJ_Ting",
    CHANGE_MJ_CARDS:"CHANGE_MJ_CARDS",
    CHANGE_MJ_BG:"CHANGE_MJ_BG",

    //娄底放炮罚
    LDFPF_DANIAO:"LDFPF_DANIAO",
    LDFPF_FINISH_DANIAO:"LDFPF_FINISH_DANIAO",
    // LDFPF_REPORT_DANIAO:"LDFPF_REPORT_DANIAO",
    LDFPF_QIHU: "LDFPF_QIHU",
    LDFPF_KAIJUXIPAI: "LDFPF_KAIJUXIPAI",
    LDFPF_FINISH_KAIJUXIPAI: "LDFPF_FINISH_KAIJUXIPAI",

    //跑的快
    PDK_DESK_HUIKAN:"PDK_DESK_HUIKAN",
    PDK_PIAOFEN:"PDK_PIAOFEN",
    PDK_FINISH_PIAOFEN:"PDK_FINISH_PIAOFEN",
    //转转麻将
    ZZMJ_PIAOFEN:"ZZMJ_PIAOFEN",
    ZZMJ_FINISH_PIAOFEN:"ZZMJ_FINISH_PIAOFEN",
    //清理上局的剩余牌
    PHZ_CLEAN_SPANEL:"PHZ_CLEAN_SPANEL",

    //飘分
    PIAO_FEN:"PIAO_FEN",
    SELECT_PIAO_FEN:"SELECT_PIAO_FEN",

    PDK_DA_NIAO:"PDK_DA_NIAO",

    //郴州字牌
    CZZP_PIAOFEN:"CZZP_PIAOFEN",
    CZZP_FINISH_PIAOFEN:"CZZP_FINISH_PIAOFEN",
    SYBP_CHUI:"SYBP_CHUI",
    SYBP_FINISH_CHUI:"SYBP_FINISH_CHUI",

    PLAY_CARD_AFTER_XIAOHU:"PLAY_CARD_AFTER_XIAOHU",

    //捉红字 
    SHOW_TING:"SHOW_TING",

    UPDATE_ROLE_LIST:"UPDATE_ROLE_LIST",//刷新当前操作的角色下级列表
    CLUB_ALLOT_USER:"CLUB_ALLOT_USER",//发送分配邀请人的请求

    //邵阳麻将
    SYMJ_JIACHUI:"SYMJ_JIACHUI",//邵阳麻将显示加锤
    SYMJ_JIACHUI_STATE:"SYMJ_JIACHUI_STATE",//邵阳麻将选择加锤
    //衡阳十胡卡
    HYSHK_KHSZP:"HYSHK_KHSZP",
    UPDATA_CLUB_CREDIT:"UPDATA_CLUB_CREDIT",//刷新亲友圈比赛分
    UPDATA_CLUB_COIN:"UPDATA_CLUB_COIN",//亲友圈金币刷新
    UPDATA_CLUB_TABLE_COIN:"UPDATA_CLUB_TABLE_COIN",//牌桌金币刷新
    SWITCH_CLUB:"SWITCH_CLUB",//切换亲友圈
    CLUB_UPGRADE_SUCCESSED:"CLUB_UPGRADE_SUCCESSED",//亲友圈玩家升级推送
    CLUB_Level_LOG:"CLUB_Level_LOG",//亲友圈玩家升级推送
    CLUB_RESULT_COIN:"CLUB_RESULT_COIN",//亲友圈结算金币
    //湘乡告胡子
    XXGHZ_DATUO:"XXGHZ_DATUO",//湘乡告胡子显示打坨
    XXGHZ_DATUO_STATE:"XXGHZ_DATUO_STATE",//湘乡告胡子选择打坨

    GetTableMsg:"GetTableMsg",//收到牌桌消息用这个发消息

    CLUB_CHECK_DOWN_TEAM:"CLUB_CHECK_DOWN_TEAM",//查看下级

    AHPHZ_UPDATE_HUXI:"AHPHZ_UPDATE_HUXI",//安化跑胡子刷新胡息

    HAIDI_GUO:"HAIDI_GUO",

    CXMJ_GANG_ID:"CXMJ_GANG_ID",//楚雄麻将杠牌ID
    CXMJ_CHOOSE_GANG:"CXMJ_CHOOSE_GANG",//楚雄麻将杠牌ID

    KWMJ_FENGDONG:"KWMJ_FENGDONG",//开王麻将封东
    KWMJ_BAOTING:"KWMJ_BAOTING",//开王麻将报听
    KWMJ_XIANJIA_OPERATE:"KWMJ_XIANJIA_OPERATE",//开局闲家有操作
    KWMJ_XIANJIA_FINISH_OPERATE:"KWMJ_XIANJIA_FINISH_OPERATE",//开局闲家操作完毕

    ZZPH_REFRESH_SCORE:"ZZPH_REFRESH_SCORE",//株洲碰胡刷新分数
    ZZPH_WUFU:"ZZPH_WUFU",//株洲碰胡五福通知
    ZZPH_WUFU_BAOJING:"ZZPH_WUFU_BAOJING",//株洲碰胡五福报警
    ZZPH_DANIAO_START:"ZZPH_DANIAO_START",//株洲碰胡打鸟
    ZZPH_DANIAO_UPDATE:"ZZPH_DANIAO_UPDATE",//株洲碰胡广播打鸟
    ZZPH_SEAT_EXCHANGE:"ZZPH_SEAT_EXCHANGE",//株洲碰胡换位置

    HBGZP_MO_PAI:"HBGZP_MO_PAI",//湖北个子牌摸牌
    HBGZP_PAOFEN_STATE:"HBGZP_PAOFEN_STATE",//湖北个子牌跑分反馈
    HBGZP_PAOFEN:"HBGZP_PAOFEN",//湖北个子牌通知跑分

    GDCSMJ_LASTCIRCLE:"GDCSMJ_LASTCIRCLE",//潮汕麻将最后一圈

    QF_DEAL_SCORE:"QF_DEAL_SCORE",
    PDK_QIE_PAI:"PDK_QIE_PAI",

    TCMJ_STARTPIAOFEN:"TCMJ_STARTPIAOFEN",//通城麻将通知飘分
    TCMJ_PIAOFENEND:"TCMJ_PIAOFENEND",//通城麻将飘分反馈

    BSMJ_SHOWBAOTING:"BSMJ_SHOWBAOTING",//保山麻将报听
    BSMJ_BAOTINGCLICK:"BSMJ_BAOTINGCLICK",//保山麻将报听反馈

    DHMJ_GANGDIPAI:"DHMJ_GANGDIPAI",//德宏麻将杠牌刷新底牌

    UPDATE_HALL_BACKGROUND:"UPDATE_HALL_BACKGROUND",//更新大厅背景
    UPFATE_SERVER_TIME:"UPFATE_SERVER_TIME",//更新服务器时间
    NEW_YEAR_ACTIVITY_NOTICE:"NEW_YEAR_ACTIVITY_NOTICE",//新年活动公告
    NEW_YEAR_ACTIVITY_HBLX:"NEW_YEAR_ACTIVITY_HBLX",//红包来袭
    XXEQS_GUOPAI:"XXEQS_GUOPAI",//湘西2710过牌数据
    MJ_HIDE_ACTION:"MJ_HIDE_ACTION",//

    TCPFMJ_BUHUA:"TCPFMJ_BUHUA",//桐城跑风麻将补花
    TCPFMJ_PAOFENG:"TCPFMJ_PAOFENG",//桐城跑风麻将跑风
    REMOVE_POP_ALL:"REMOVE_POP_ALL",//系统返回关闭
    YYWHZ_SHENPAI:"YYWHZ_SHENPAI",//益阳歪胡子第一局神牌数据
    
    YYWHZ_YAOPAI:"YYWHZ_YAOPAI",//益阳歪胡子胡牌显示腰牌数据
    YYNXMJ_BAOTING:"YYNXMJ_BAOTING",//南县麻将报听
    YYNXMJ_HAIDI:"YYNXMJ_HAIDI",//南县麻将海底
    
    CQXZMJ_START_HUANZHANG:"CQXZMJ_START_HUANZHANG",//重庆血战麻将开始换张
    CQXZMJ_SUCESS_HUANZHANG:"CQXZMJ_SUCESS_HUANZHANG",//重庆血战麻将成功换张
    CQXZMJ_FINISH_HUANZHANG:"CQXZMJ_FINISH_HUANZHANG",//重庆血战麻将结束换张
    CQXZMJ_CHECK_HUANZHANG:"CQXZMJ_CHECK_HUANZHANG",//重庆血战麻将检查能否换张

    CQXZMJ_START_DINGQUE:"CQXZMJ_START_DINGQUE",//重庆血战麻将开始定缺
    CQXZMJ_SUCESS_DINGQUE:"CQXZMJ_SUCESS_DINGQUE",//重庆血战麻将开始定缺
    CQXZMJ_FINISH_DINGQUE:"CQXZMJ_FINISH_DINGQUE",//重庆血战麻将结束定缺
    CQXZMJ_SCOREBOARD:"CQXZMJ_SCOREBOARD",//重庆桌面战绩

    CLUB_WZQ_CREATEROOM:"CLUB_WZQ_CREATEROOM",//五子棋创建房间
    CLUB_WZQ_SELECT_SCORE_TYPE:"CLUB_WZQ_SELECT_SCORE_TYPE",//五子棋提示选分面板
    CLUB_WZQ_SELECT_SCORE:"CLUB_WZQ_SELECT_SCORE",//五子棋选分

    REMOVE_SET_POP:"REMOVE_SET_POP",
    GOLD_PYQ_LIST:"GOLD_PYQ_LIST",
    GOID_AREA_GAMES:"GOID_AREA_GAMES",
    GOID_AREA_CONFIG:"GOID_AREA_CONFIG",
    GOLD_VIEW_REFRESH:"GOLD_VIEW_REFRESH",//刷新金币场大厅界面
    GOLD_EXCHANGE_LIST:"GOLD_EXCHANGE_LIST",//商城兑换白金豆列表
    GOLD_UPDATE_CONFIG_COMMON:"GOLD_UPDATE_CONFIG_COMMON",//刷新常用的玩法列表
    REFRESH_QIANDAO:"REFRESH_QIANDAO",
    MISSION_STATUS:"MISSION_STATUS",
    QTJ_YJBJ:"QTJ_YJBJ",//群统计一键标记

    UPDATE_NAME_CHANGE:"UPDATE_NAME_CHANGE",
    GOLD_MATCH_JOIN_ROOM:"GOLD_MATCH_JOIN_ROOM",//金币比赛场加入房间获取playingRoomId
    GOLD_MATCH_UPDATE_RANK:"GOLD_MATCH_UPDATE_RANK",//金币比赛场房间更新排名
    GOLD_MATCH_UPDATE_NUMBER:"GOLD_MATCH_UPDATE_NUMBER",//更新报名人数
    GOLD_MATCH_UPDATE_RESULT_STATE:"GOLD_MATCH_UPDATE_RESULT_STATE",//金币比赛场结算状态更新
    GOLD_MATCH_FLOW:"GOLD_MATCH_FLOW",//比赛场流局

    XPPHZ_GUCHOU:"XPPHZ_GUCHOU",//溆浦跑胡子 箍臭
    GOLDEN_EGGS:"GOLDEN_EGGS",//砸金蛋
    GOLDEN_EGGS_OPEN:"GOLDEN_EGGS_OPEN",//砸开返回
    GOLDEN_EGGS_INVITE:"GOLDEN_EGGS_INVITE",//砸金蛋邀请信息
    NEW_CARNIVAL_ICON:"NEW_CARNIVAL_ICON",//新人狂欢图标
    NEW_CARNIVAL_GUIDE:"NEW_CARNIVAL_GUIDE",//新人狂欢引导
    NEW_CARNIVAL_REFRESH:"NEW_CARNIVAL_REFRESH",//刷新新人狂欢

    BISAI_XIPAI:"BISAI_XIPAI",//比赛场洗牌
    REFRESH_USERDATA_POWERMANAGE: "REFRESH_USERDATA_POWERMANAGE",//权限管理界面刷新
    DELETE_USERDATA_POWERMANAGE: "DELETE_USERDATA_POWERMANAGE",//权限管理界面删除成员
    ADD_USERDATA_POWERMANAGE: "ADD_USERDATA_POWERMANAGE",//权限管理界面添加成员
    MATCHSCOREWARNING_ADD_USER: "MATCHSCOREWARNING_ADD_USER",//团队预警分数添加成员
    MATCHSCOREWARNING_DELETE_USER: "MATCHSCOREWARNING_DELETE_USER",//团队预警分数删除成员
    MATCHSCOREWARNING_MODIFY_WARNINGSCORE: "MATCHSCOREWARNING_MODIFY_WARNINGSCORE",//修改预警分

}

/**
 * 事件管理分发
 * @type {{addEventListener: Function, removeListener: Function, dispatchEvent: Function}}
 */
var SyEventManager = {
    /**
     * 添加事件监听<br>
     * e.g. var listener = EventUtil.addEventListener(EventType.HIDE_BASE_POP_PANEL, this, this.onClose);
     * @param eventType
     * @param target
     * @param selector
     * @returns listener
     */
    addEventListener:function(eventType,target,selector){
        //监听listview改变事件
        var listener = cc.EventListener.create({
            event: cc.EventListener.CUSTOM,
            eventName: eventType,
            callback: function(event){
                if(selector){
                    selector.call(target,event);
                }
            }
        });
        cc.eventManager.addListener(listener, target);
        return listener;
    },

    /**
     * 移除事件监听
     * @param listener
     */
    removeListener:function(listener){
        // cc.log("removeListener",JSON.stringify(listener))
        if(listener){
            cc.eventManager.removeListener(listener);
        }
    },

    /**
     * 广播分发事件
     * @param eventType
     * @param userData
     */
    dispatchEvent:function(eventType,userData){
        var event = new cc.EventCustom(eventType);
        event.setUserData(userData);
        cc.eventManager.dispatchEvent(event);
    },

    dispatchTableEvent:function(type,userData){
        var event = new cc.EventCustom(SyEvent.GetTableMsg);
        event.eventType = type;
        event.setUserData(userData);
        cc.eventManager.dispatchEvent(event);
    }
}