/**
 * Created by Administrator on 2020/1/7.1
 */
var jsList = [
    "src/src_mj/MJSyVersion.js",
    "src/src_mj/MajiangHuBean.js",
    "src/src_mj/MajiangSmartFilter.js",
    "src/src_mj/MajiangIndexArr.js",
    "src/src_mj/MJAI.js",
    "src/src_mj/MJRoomSound.js",
    "src/src_mj/MJRoomEffects.js",
    "src/src_mj/MJEffectLayout.js",
    "src/src_mj/Mahjong.js",
    "src/src_mj/MJHaiDiPop.js",
    "src/src_mj/MJGangPop.js",
    "src/src_mj/MJReplay.js",
    "src/src_mj/MJPlayer.js",
    "src/src_mj/MJReplayModel.js",
    "src/src_mj/MJRoomModel.js",
    "src/src_mj/MJSmallResultOther.js",

    "src/src_mj/src_zzmj/ZZMajiangHuBean.js",
    "src/src_mj/src_zzmj/ZZMajiangSmartFilter.js",
    "src/src_mj/src_zzmj/ZZMahjong.js",
    "src/src_mj/src_zzmj/ZZMJLayout.js",
    "src/src_mj/src_zzmj/ZZMJReplayLayout.js",
    "src/src_mj/src_zzmj/ZZMJReplay.js",
    "src/src_mj/src_zzmj/ZZMJRoom.js",
    "src/src_mj/src_zzmj/ZZMJBigResultPop.js",
    "src/src_mj/src_zzmj/ZZMJSmallResultPop.js",

    "src/src_mj/src_yzwdmj/YZWDMajiangHuBean.js",
    "src/src_mj/src_yzwdmj/YZWDMajiangSmartFilter.js",
    "src/src_mj/src_yzwdmj/YZWDMahjong.js",
    "src/src_mj/src_yzwdmj/YZWDMJLayout.js",
    "src/src_mj/src_yzwdmj/YZWDMJReplayLayout.js",
    "src/src_mj/src_yzwdmj/YZWDMJReplay.js",
    "src/src_mj/src_yzwdmj/YZWDMJRoom.js",
    "src/src_mj/src_yzwdmj/YZWDMJSmallResultPop.js",
    "src/src_mj/src_yzwdmj/YZWDMJBigResultPop.js",

    "src/src_mj/src_yjmj/YJMajiangHuBean.js",
    "src/src_mj/src_yjmj/YJMajiangSmartFilter.js",
    "src/src_mj/src_yjmj/YJMahjong.js",
    "src/src_mj/src_yjmj/YJMJLayout.js",
    "src/src_mj/src_yjmj/YJMJReplayLayout.js",
    "src/src_mj/src_yjmj/YJMJReplay.js",
    "src/src_mj/src_yjmj/YJMJRoom.js",
    "src/src_mj/src_yjmj/YJMJSmallResultPop.js",
    "src/src_mj/src_yjmj/YJMJBigResultPop.js",

    "src/src_mj/src_symj/SYMahjong.js",
    "src/src_mj/src_symj/SYMJLayout.js",
    "src/src_mj/src_symj/SYMJReplayLayout.js",
    "src/src_mj/src_symj/SYMJReplay.js",
    "src/src_mj/src_symj/SYMJRoom.js",
    "src/src_mj/src_symj/SYMJSmallResultPop.js",
    "src/src_mj/src_symj/SYMJBigResultPop.js",

    "src/src_mj/src_cqxzmj/CQXZMahjong.js",
    "src/src_mj/src_cqxzmj/CQXZMJLayout.js",
    "src/src_mj/src_cqxzmj/CQXZMJReplayLayout.js",
    "src/src_mj/src_cqxzmj/CQXZMJReplay.js",
    "src/src_mj/src_cqxzmj/CQXZMJRoom.js",
    "src/src_mj/src_cqxzmj/CQXZMJSmallResultPop.js",
    "src/src_mj/src_cqxzmj/CQXZMJBigResultPop.js",

    "src/src_mj/src_hzmj/HZMajiangHuBean.js",
    "src/src_mj/src_hzmj/HZMajiangSmartFilter.js",
    "src/src_mj/src_hzmj/HZMahjong.js",
    "src/src_mj/src_hzmj/HZMJLayout.js",
    "src/src_mj/src_hzmj/HZMJReplayLayout.js",
    "src/src_mj/src_hzmj/HZMJReplay.js",
    "src/src_mj/src_hzmj/HZMJRoom.js",
    "src/src_mj/src_hzmj/HZMJSmallResultPop.js",
    "src/src_mj/src_hzmj/HZMJBigResultPop.js",

    "src/src_mj/src_csmj/CSMajiangHuBean.js",
    "src/src_mj/src_csmj/CSMajiangSmartFilter.js",
    "src/src_mj/src_csmj/CSMahjong.js",
    "src/src_mj/src_csmj/CSMJLayout.js",
    "src/src_mj/src_csmj/CSMJReplayLayout.js",
    "src/src_mj/src_csmj/CSMJReplay.js",
    "src/src_mj/src_csmj/CSMJRoom.js",
    "src/src_mj/src_csmj/CSMJSmallResultPop.js",
    "src/src_mj/src_csmj/CSMJBigResultPop.js",

    "src/src_mj/src_bsmj/BSMajiangHuBean.js",
    "src/src_mj/src_bsmj/BSMajiangSmartFilter.js",
    "src/src_mj/src_bsmj/BSMahjong.js",
    "src/src_mj/src_bsmj/BSMJLayout.js",
    "src/src_mj/src_bsmj/BSMJReplayLayout.js",
    "src/src_mj/src_bsmj/BSMJReplay.js",
    "src/src_mj/src_bsmj/BSMJRoom.js",
    "src/src_mj/src_bsmj/BSMJSmallResultPop.js",
    "src/src_mj/src_bsmj/BSMJBigResultPop.js",

    "src/src_mj/src_ahmj/AHMajiangHuBean.js",
    "src/src_mj/src_ahmj/AHMajiangSmartFilter.js",
    "src/src_mj/src_ahmj/AHMahjong.js",
    "src/src_mj/src_ahmj/AHMJPlayer.js",
    "src/src_mj/src_ahmj/AHMJLayout.js",
    "src/src_mj/src_ahmj/AHMJReplayLayout.js",
    "src/src_mj/src_ahmj/AHMJReplay.js",
    "src/src_mj/src_ahmj/AHMJRoom.js",
    "src/src_mj/src_ahmj/AHMJSmallResultPop.js",
    "src/src_mj/src_ahmj/AHMJBigResultPop.js",

    "src/src_mj/src_csmj/NYMJMaPai.js",
    "src/src_mj/src_tjmj/TJMJRoom.js",
    "src/src_mj/src_tjmj/TJMJLayout.js",

    "src/src_mj/src_dzmj/DZMJLayout.js",
    "src/src_mj/src_dzmj/DZMJRoom.js",
    "src/src_mj/src_dzmj/DZMJSmallResultPop.js",

    "src/src_mj/src_yymj/YYMJRoom.js",
    "src/src_mj/src_yymj/YYMJSmallResultPop.js",

    "src/src_mj/src_zjmj/ZJMJRoom.js",
    "src/src_mj/src_zjmj/ZJMJLayout.js",
    "src/src_mj/src_zjmj/ZJMJSmallResultPop.js",
];